#!/bin/bash
jupyter serverextension enable --py nbserverproxy --sys-prefix
jupyter labextension install @jupyter-widgets/jupyterlab-manager \
                             @jupyterlab/hub-extension@0.12 \
                             @pyviz/jupyterlab_pyviz \
                             jupyter-leaflet \
                             dask-labextension


# Julia stuff
# https://stackoverflow.com/questions/51272077/install-julia-packages-via-command-line/51273146
# https://github.com/JuliaLang/IJulia.jl
# https://github.com/JuliaLang/IJulia.jl/issues/717
julia -e 'ENV["JUPYTER"]="jupyter";
          using Pkg;
          Pkg.add(["IJulia", "MeshArrays"]);
          Pkg.build("ZMQ");'

#EOF
