#!/usr/bin/env bash
set -euo pipefail

# need a config that works on both binder and hub
if [ ! -f /srv/repo/.dask/dask_config.yaml ]; then
    export DASK_ROOT_CONFIG=/srv/repo/.dask/config.yaml
fi

cd ${HOME}

exec "$@"
